<div id="horizontal-menu">
    <?php $page = $C->request->input('p')?>
    <div class="menu-container">
        <div class="menu " role="tablist">
            <a href="#languages" data-toggle="tab" class="menu-item  <?php echo (!$page) ? 'active' : null?>"><span><?php _l('words')?></span></a>
            <a href="#new" data-toggle="tab" class="menu-item   <?php echo ($page == 'new') ? 'active' : null?>"><span><?php _l('add-new-word')?></span></a>
            <a href="<?php echo getFullUrl()?>?action=update"  class="menu-item ajax-action   btn btn-primary btn-sm"><span style="color: #ffffff !important;"><?php _l('update-words')?></span></a>

        </div>
    </div>

    <div class="actions-pane">
        <ul class="clearfix">
            <li>
                <form action="<?php echo getFullUrl()?>" data-container="#languages" method="post" class="search-form">
                    <div class="input-group">

                        <input placeholder="<?php _l('enter-a-keyword')?>" type="text" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
                        <div class="input-group-append">
                            <button class="input-group-text btn btn-primary" id="inputGroupPrepend2"><i class="la la-search"></i></button>
                        </div>
                    </div>
                </form>
            </li>

        </ul>
    </div>
</div>

<div class="content">
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show <?php echo (!$page) ? 'active' : null?>" id="languages" role="tabpanel" >
            <?php echo view('admin/languages/display-translate', array('languages' => $languages))?>
        </div>

        <div class="tab-pane fade show <?php echo ($page == 'new') ? 'active' : null?>" id="new" role="tabpanel" >
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                <input type="hidden" name="val[create]" value="1"/>
                <div class="form-group">
                    <label><?php _l('word-key')?></label>
                    <input type="text" class="form-control" name="val[lang_key]"/>
                </div>
                <div class="form-group">
                    <label><?php _l('word')?></label>
                    <input type="text" class="form-control" name="val[word]"/>
                </div>




                <button class="btn btn-primary btn-lg"><?php _l('submit')?></button>

            </form>
        </div>

    </div>
</div>