<form action="<?php echo getFullUrl(true)?>" class="general-form" method="post" id="pages-list-form">
    <input type="hidden" value="1" name="val[bulk_action]"/>
    <div class="modern-table">
        <div class="table-head clearfix">
            <div class="each" style="width:5%;">
                <a href="javascript:void(0)" onclick="submitForm('#pages-list-form', 'bulk')" class="btn btn-light"><i class="la la-trash"></i></a>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('options')?>
            </div>
            <div class="each" style="width: 30%;">
                <?php _l('name')?>
            </div>
            <div class="each" style="width: 25%;">
                <?php _l('slug')?>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('status')?>
            </div>
            <div class="each" style="width: 20%;">
                <?php _l('created')?>
            </div>
        </div>


        <div class="table-body" >

            <?php foreach($pages->results() as $page):?>
                <div class="table-row clearfix">
                    <div class="each" style="width: 5%;">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="val[id][]" value="<?php echo $page['id']?>" class="custom-control-input" id="customCheck<?php echo $page['id']?>">
                            <label class="custom-control-label" for="customCheck<?php echo $page['id']?>"></label>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 10%;">
                       <div class="left">
                           <?php _l('options')?>
                       </div>
                        <div class="right">
                            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                <a href="<?php echo url('admin/page/edit/'.$page['id'])?>" data-ajax="true" class="btn btn-light"><i class="la la-pencil-alt"></i></a>
                                <div class="btn-group" role="group">
                                    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                        <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/pages', array('action' => 'delete','id' => $page['id']))?>"><?php _l('delete')?></a>
                                        <?php if($page['status']):?>
                                            <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/pages', array('action' => 'disable','id' => $page['id']))?>"><?php _l('disable')?></a>
                                        <?php else:?>
                                            <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/pages', array('action' => 'enable','id' => $page['id']))?>"><?php _l('enable')?></a>
                                        <?php endif?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 30%;">
                        <div class="left">
                            <?php _l('name')?>
                        </div>
                        <div class="right">
                            <?php echo $page['name']?>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 25%;">
                        <div class="left">
                            <?php _l('slug')?>
                        </div>
                        <div class="right">
                            <?php echo $page['slug']?>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 10%;">
                        <div class="left">
                            <?php _l('status')?>
                        </div>
                        <div class="right">
                            <?php if($page['status']):?>
                                <span class="badge badge-success"><?php _l('active')?></span>
                            <?php else:?>
                                <span class="badge badge-secondary"><?php _l('not-active')?></span>
                            <?php endif?>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 20%;">
                        <div class="left">
                            <?php _l('created')?>
                        </div>
                        <div class="right">
                            <?php echo date('M d, Y', $page['created'])?>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
</form>

<?php if($pages->total < 1):?>
    <div class="empty-content">
        <i class="la la-fill"></i>
        <span><?php _l('no-contents-show')?></span>
    </div>
<?php else:?>
    <?php echo $pages->links(array('term' => $C->request->input('term')))?>
<?php endif?>