<div id="horizontal-menu">
    <div class="menu-container">
        <div class="menu " role="tablist">
            <a href="#page" data-toggle="tab" class="menu-item  active"><span><?php _l('edit-page')?></span></a>
            <a href="<?php echo url('admin/pages?p=new')?>" data-ajax="true"  class="menu-item  "><span><?php _l('add-new-page')?></span></a>

        </div>
    </div>

    <div class="actions-pane">
        <ul class="clearfix">
            <li>
                <form action="<?php echo getFullUrl()?>" data-container="#users" method="post" class="search-form">
                    <div class="input-group">

                        <input placeholder="<?php _l('enter-a-keyword')?>" type="text" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
                        <div class="input-group-append">
                            <button class="input-group-text btn btn-primary" id="inputGroupPrepend2"><i class="la la-search"></i></button>
                        </div>
                    </div>
                </form>
            </li>

        </ul>
    </div>
</div>

<div class="content">
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="page" role="tabpanel" >
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form" style="max-width: 800px">
                <input type="hidden" name="val[create]" value="1"/>
                <div class="form-group">
                    <label><?php _l('name')?></label>
                    <input type="text" value="<?php echo $page['name']?>" class="form-control" name="val[name]"/>
                </div>



                <div class="form-group">
                    <label class="mb-4"><?php _l('position')?></label>
                    <div class="">

                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" value="header" <?php echo ($page['position'] == 'header') ? 'checked':null?>  id="customRadioInline1" name="val[position]" class="custom-control-input">
                            <label class="custom-control-label" for="customRadioInline1"><?php _l('header-menu')?></label>
                        </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" value="footer"  <?php echo ($page['position'] == 'footer') ? 'checked':null?>  id="customRadioInline2" name="val[position]" class="custom-control-input">
                            <label class="custom-control-label" for="customRadioInline2"><?php _l('footer-menu')?></label>
                        </div>

                    </div>

                </div>
                <div class="form-group">
                    <label class="mb-2"><?php _l('page-content')?></label>

                    <div class="">
                        <textarea id="text-editor" name="val[content]" ><?php echo $page['content']?></textarea>
                    </div>
                </div>


                <button class="btn btn-primary btn-lg"><?php _l('save-changes')?></button>

            </form
        </div>
    </div>
</div>