<!-- <div class="clearfix">
    <a href="<?php echo url('login')?>" data-ajax="true" class="auth-btn float-right btn btn-outline-primary rounded"><?php _l('login')?></a>
</div> -->
<div class=" pt-5 p-4">
    <div class="col-md-1"></div>
    <div class="p-2">
        <h2><strong><?php _l('Hello')?></strong></h2>
    </div>
    <div class="text-primary p-2">
        <h1><strong><?php _l('ADSVIATE')?></strong></h1>
    </div>
    <div  class="p-2 pt-1">
        <h7><strong>Let's make social media good again</strong></h7>
    </div>


<div class="cmt-3 mt-2 bg-primary">
    <a class="btn btn-block btn-primary" style="color:white !important;text-decoration:none !important" href="<?php echo url('signup')?>">Create</a>
</div>
</div>


