<div id="auth-container" class="auth-container-alt clearfix">
    <div class="right-pane">
        <a href="<?php echo url()?>" class="logo"><img src="<?php echo config('site_logo', 'assets/images/logo.png')?>"/> </a>
        <?php echo $content?>

        <?php if(config('facebook-login', false) or config('twitter-login', false) or config('google-login', false)):?>
            <div class="social-auth">
                <p><?php _l('or')?></p>

                <h6><?php _l('signin-with')?></h6>

                <div class="mt-3">
                    <?php if(config('facebook-login', false)):?>
                        <a href="<?php echo url('facebook/auth')?>" class="facebook-link"><i class="lab la-facebook-f"></i></a>
                    <?php endif?>
                    <?php if(config('twitter-login', false)):?>
                        <a href="<?php echo url('twitter/auth')?>" class="twitter-link"><i class="lab la-twitter"></i></a>
                    <?php endif?>
                    <?php if(config('google-login', false)):?>
                        <a href="<?php echo url('google/auth')?>" class="google-link"><img style="width:25px !important;" src="<?php echo assetUrl('assets/images/google.png')?>"/></a>
                    <?php endif?>
                </div>
            </div>
        <?php endif?>
    </div>
    <div class="left-pane start-page">
        <div class="cover"></div>
    </div>

</div>