<h6><?php _l('bulk-schedule')?></h6>
<div class="row mb-3">

    <div class="col-md-6">
        <div class="custom-control custom-checkbox ">
            <input type="hidden" name="val[permission][bulk-schedule]" value="0"/>
            <input type="checkbox"  value="1" name="val[permission][bulk-schedule]" <?php echo (isset($permissions['bulk-schedule']) and $permissions['bulk-schedule']) ? 'checked': null?>  class="custom-control-input" id="customCheckbulk-schedule">
            <label class="custom-control-label" for="customCheckbulk-schedule"><?php _l('enable')?></label>
        </div>
    </div>


</div>