<form action="<?php echo getFullUrl(true)?>" class="general-form" method="post" id="proxy-list-form">
    <input type="hidden" value="1" name="val[bulk_action]"/>
    <div class="modern-table">
        <div class="table-head clearfix">
            <div class="each" style="width:5%;">
                <a href="javascript:void(0)" onclick="submitForm('#proxy-list-form', 'bulk')" class="btn btn-light"><i class="la la-trash"></i></a>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('options')?>
            </div>
            <div class="each" style="width: 40%;">
                <?php _l('address')?>
            </div>
            <div class="each" style="width: 15%;">
                <?php _l('location')?>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('status')?>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('used')?>
            </div>
            <div class="each" style="width: 10%;">
                <?php _l('created')?>
            </div>
        </div>

        <?php
            $modalContent = '';
        ?>


        <div class="table-body" >

            <?php foreach($proxies->results() as $proxy):?>
                <?php
                    $countries = '<select class="form-control" name="val[location]"><option value="">'.l('unknown').'</option>';
                    foreach (getCountries() as $country){
                        $active = ($proxy['location'] == $country) ? 'selected' : '';
                        $countries .= '<option '.$active.' value="'.$country.'">'.$country.'</option>';
                    }
                    $countries .= "</select>";
                    $modalContent .= '<div class="modal" tabindex="-1" role="dialog" id="proxyEditModal'.$proxy['id'].'">
                    <form action="'.getFullUrl(true).'" class="general-form" method="post" >
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">'.l('edit-proxy').'</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body proxy-modal-body" >
                                <input type="hidden" name="val[edit]" value="'.$proxy['id'].'"/>
                <div class="form-group">
                    <label>'.l('proxy-address').'</label>
                    <input type="text" class="form-control" name="val[address]" value="'.$proxy['address'].'"/>

                    <span class="text-muted">'.l('proxy-address-info').'</span>
                </div>

                <div class="form-group">
                    <label>'.l('usage-limit').'</label>
                    <input type="number"  class="form-control" name="val[limit]" value="'.$proxy['usage_limit'].'"/>
                </div>

                <div class="form-group">
                    <label>'.l('location').'</label>
                    '.$countries.'
                </div>

                ';
                    $modalContent .= Hook::getInstance()->fire('proxy.address.edit', null, array($proxy));

                           $modalContent .='</div>
                            <div class="modal-footer">
                                
                                <button  class="btn btn-primary">'.l('save-changes').'</button>
                            </div>
                        </div>
                    </div></form>
                </div>';
                ?>
                <div class="table-row clearfix">
                    <div class="each " style="width: 5%;">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" name="val[id][]" value="<?php echo $proxy['id']?>" class="custom-control-input" id="customCheck<?php echo $proxy['id']?>">
                            <label class="custom-control-label" for="customCheck<?php echo $proxy['id']?>"></label>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 10%;">
                        <div class="left">
                            <?php _l('options')?>
                        </div>
                        <div class="right">
                            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                                <a href="" data-toggle="modal" data-target="#proxyEditModal<?php echo $proxy['id']?>" class="btn btn-light"><i class="la la-eye"></i></a>
                                <div class="btn-group" role="group">
                                    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                        <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/proxy', array('action' => 'delete','id' => $proxy['id']))?>"><?php _l('delete')?></a>
                                        <?php if($proxy['status']):?>
                                            <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/proxy', array('action' => 'disable','id' => $proxy['id']))?>"><?php _l('disable')?></a>
                                        <?php else:?>
                                            <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/proxy', array('action' => 'enable','id' => $proxy['id']))?>"><?php _l('enable')?></a>
                                        <?php endif?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 40%;">
                        <div class="left">
                            <?php _l('address')?>
                        </div>
                        <div class="right">
                            <?php echo $proxy['address']?>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 15%;">
                        <div class="left">
                            <?php _l('location')?>
                        </div>
                        <div class="right">
                            <?php echo $proxy['location']?>
                        </div>
                    </div>
                    <div class="each clearfix" style="width: 10%;">
                        <div class="left">
                            <?php _l('status')?>
                        </div>
                        <div class="right">
                            <?php if($proxy['status']):?>
                                <span class="badge badge-success"><?php _l('active')?></span>
                            <?php else:?>
                                <span class="badge badge-secondary"><?php _l('not-active')?></span>
                            <?php endif?>
                        </div>
                    </div>
                    <div class="each" style="width: 10%;">
                        <div class="left">
                            <?php _l('used')?>
                        </div>
                        <div class="right">
                            <?php echo model('proxy')->countProxyUsed($proxy['id'])?>
                        </div>
                    </div>
                    <div class="each" style="width: 10%;">
                        <div class="left">
                            <?php _l('created')?>
                        </div>
                        <div class="right">
                            <?php echo date('M d, Y', $proxy['created'])?>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
</form>

<?php if($proxies->total < 1):?>
    <div class="empty-content">
        <i class="la la-fill"></i>
        <span><?php _l('no-contents-show')?></span>
    </div>
<?php else:?>
    <?php echo $proxies->links(array('term' => $C->request->input('term')))?>
<?php endif?>

<?php echo $modalContent?>
