<div class="caption-container">

   <div class="page-title-panel d-flex align-items-center">
      <div><h2><?php _l('captions')?></h2></div>
      <div class="ml-auto">
          <a href="#new" data-toggle="tab" class="menu-item btn   <?php echo ($page == 'new') ? 'active' : null?>"><span><?php _l('add-new-caption')?></span></a> 
      </div>
   </div>

   <div id="horizontal-menu" class="d-none">
      <?php $page = $C->request->input('p')?>
      <div class="menu-container">
         <div class="menu " role="tablist">
            <a href="#captions" data-toggle="tab" class="menu-item  <?php echo (!$page) ? 'active' : null?>"><span><?php _l('captions')?></span></a>
            <a href="#new" data-toggle="tab" class="menu-item   <?php echo ($page == 'new') ? 'active' : null?>"><span><?php _l('add-new-caption')?></span></a>
         </div>
      </div>
      <div class="actions-pane">
         <ul class="clearfix">
            <li>
               <form action="<?php echo getFullUrl()?>" data-container="#captions" method="post" class="search-form">
                  <div class="input-group">
                     <input placeholder="<?php _l('enter-a-keyword')?>" value="<?php echo $C->request->input('term')?>" type="text" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
                     <div class="input-group-append">
                        <button class="input-group-text btn btn-primary" id="inputGroupPrepend2"><i class="la la-search"></i></button>
                     </div>
                  </div>
               </form>
            </li>
         </ul>
      </div>
   </div>

   <div class="content">
      <div class="tab-content" id="myTabContent">
         <div class="tab-pane fade show <?php echo (!$page) ? 'active' : null?>" id="captions" role="tabpanel" >
            <?php echo view('caption/display', array('captions' => $captions))?>
         </div>
         <div class="tab-pane fade show <?php echo ($page == 'new') ? 'active' : null?>" id="new" role="tabpanel" >
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
               <input type="hidden" name="val[create]" value="1"/>
               <div class="form-group">
                  <label><?php _l('title')?></label>
                  <input type="text" class="form-control" name="val[title]"/>
               </div>
               <div class="form-group">
                  <label><?php _l('caption')?></label>
                  <textarea class="emoji-text form-control" name="val[content]" rows="5"></textarea>
               </div>
               <button class="btn btn-primary" ><?php _l('add-caption')?></button>
            </form>
         </div>
      </div>
   </div>

</div>
