<div class="item sort file-item-<?php echo $file['id']?>" style="position: relative">

    <div class="item-pane each-file-pane <?php echo (isset($selected) and $selected) ? 'selected' : null?>"
         onclick="fileSelected(this)"

         data-raw="<?php echo $file['file_name']?>"
         data-id="<?php echo $file['id']?>"
         data-file="<?php echo assetUrl($file['file_name'])?>" data-type="<?php echo $file['file_type']?>">
        <input type="hidden" value="<?php echo $file['id']?>" name="val[filesi][]"/>
        <div class="video-content" style="width:100%;height:100%;overflow: hidden;position:relative;">
            <?php if($file['file_type'] == 'video'):?>

            <?php endif?>
        </div>
        <div style="display: none;"><input type="checkbox" value="<?php echo $file['id']?>" name="val[files][]"/></div>

        <div class="the-content">
            <span class="badge badge-primary"><?php echo ($file['file_type'] == 'image') ? l('image') : l('video')?></span>


        </div>
    </div>
    <?php if($file['file_type'] == 'image' and model('user')->hasPermission('image-editor')):?>
        <div style="position: absolute;z-index: 99;bottom:10px;right:10px;">
            <a class="btn btn-light" style="padding:3px 5px;border: solid 1px #000;" onclick="return openImageEditor('<?php echo $file['id']?>')" href=""><i class="las la-pencil-alt"></i></a>
        </div>
    <?php endif?>
    <div class="dropdown " style="position:absolute;z-index: 9999;top: 5px;right: 10px;">
        <a href="" style="font-size: 25px;background:#fff;border:solid 2px #D3D3D3;border-radius:100px;padding:2px 2px;color:#000" data-toggle="dropdown" class="dropdown-toggle" ><i class="la la-ellipsis-v"></i></a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" onclick="return previewFile(this,'<?php echo assetUrl($file['file_name'])?>','<?php echo $file['file_type']?>')" href="#"><?php _l('view')?></a>

            <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('file-manager', array('action' => 'delete','id' => $file['id']))?>"><?php _l('delete')?></a>
        </div>
    </div>
</div>