<h6><?php _l('others')?></h6>



<div class="form-group">
    <label><?php _l('graphic-special-category-id')?></label>
    <input type="text" class="form-control" value="<?php echo config('special_category', 1)?>" name="val[special_category]"/>
</div>

<div class="form-group">
    <label><?php _l('graphic-special-category-description')?></label>
    <input type="text" class="form-control" value="<?php echo config('auto-description')?>" name="val[auto-description]"/>
</div>