<div id="horizontal-menu">
    <?php $page = $C->request->input('p')?>
    <div class="menu-container">
        <div class="menu " role="tablist">
            <a href="#accounts" data-toggle="tab" class="menu-item  active"><span>Google <?php echo strtolower(l('accounts'))?></span></a>
            <?php if(model('user')->isAdmin()):?>
                <a href="<?php echo url('admin/social/integration', array('page' => 'google'))?>" data-ajax="true"  class="menu-item hide-mobile-sm"><span><?php echo l('settings')?></span></a>
            <?php endif?>
            <a href="<?php echo url('accounts/google', array('auth' => true))?>"  class="menu-item ajax-action "><span><?php _l('add-new-account')?></span></a>

        </div>
    </div>

</div>

<div class="content">
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="accounts" role="tabpanel" >
            <div class="grid-container clearfix">
                <div class="each-container">
                    <a  href="<?php echo url('accounts/google', array('auth' => true))?>" class="each each-add ajax-action">
                        <i class="las la-plus"></i>
                        <?php _l('add-account')?>
                    </a>
                </div>
                <?php foreach ($accounts as $account): ?>
                    <div class="each-container its-account">
                        <div class="each">
                            <div class="info">
                                <?php if($account['status']):?>
                                    <span class="badge badge-success"><?php _l('active')?></span>
                                <?php else:?>
                                    <span class="badge badge-secondary"><?php _l('not-active')?></span>
                                <?php endif?>
                            </div>
                            <img src=" <?php echo assetUrl($account['avatar'])?>" style="border-radius:100px">
                            <p>
                                <?php echo $account['username']?>
                            </p>
                            <div class="actions">
                                <a class="confirm" data-ajax-action="true" href="<?php echo url('account/action',array('action' => 'delete','id' => $account['id']))?>"><i class="las la-trash-alt"></i></a>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>



            </div>
        </div>

    </div>
</div>

<?php if($details):?>
    <div class="modal fade" id="googleSelectModal" style="height: 100vh;" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <form action="<?php echo getFullUrl()?>" method="post" class="general-form">
                <input type="hidden" name="val[add]" value="1"/>
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle"><?php _l('select-business')?></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="conten" style="padding: 10px;height:400px;max-height: 400px;overflow: auto;overflow-x: hidden">
                            <div class="form-group">
                                <label><?php _l('select-account')?></label>
                                <select name="val[name]" onchange="return fetchGBLocations(this)" class="form-control">
                                    <option ><?php _l('select-account')?></option>
                                    <?php if($details):?>
                                        <?php foreach($details['accounts'] as $account):?>
                                            <option value="<?php echo $account->name?>"><?php echo $account->accountName?></option>
                                        <?php endforeach?>
                                    <?php endif?>
                                </select>
                            </div>

                            <div class="locations-container">

                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php _l('cancel')?></button>
                        <button type="submit" class="btn btn-primary" id="google-btn-submit" disabled><?php _l('submit')?></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif?>




