<?php if(config('user-signup', true)):?>
<div class="clearfix d-none" style="z-index:999999">
   <a href="<?php echo url('signup')?>"  data-ajax="true" class="auth-btn float-right btn btn-outline-primary rounded"><?php _l('signup')?></a>
</div>
<?php endif?>
<div class="welcome-title">
   <h5><?php _l('Login Now')?> !</h5>
   <h6><?php _l('Please login to continue using ADSVIATE')?></h6>
</div>
<div class="social-login">

   <div class="row">
      <div class="col-12">
         <p class="top-line">Enter via social networks</p>
      </div>
      <div class="col-6">
         <button class="btn btn-twitter">
            <svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" class="svg-inline--fa fa-twitter fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
               <path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path>
            </svg>
         </button>
      </div>
      <div class="col-6">
         <button class="btn btn-facebook">
            <svg aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-square" class="svg-inline--fa fa-facebook-square fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
               <path fill="currentColor" d="M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z"></path>
            </svg>
         </button>
      </div>
      <div class="col-12">
         <p class="bottom-line">or login with email</p>
      </div>
   </div>
</div>
<form action="<?php echo getFullUrl(true)?>" method="post" class="general-form">
   <div class="form-group">
      <label><?php _l('email-address')?></label>
      <div class="input-group mb-2">
         <div class="input-group-prepend">
            <div class="input-group-text"><i class="la la-user"></i></div>
         </div>
         <input type="text" placeholder="<?php _l('email-address')?>" class="form-control" name="val[email]" >
      </div>
   </div>
   <div class="form-group">
      <label><?php _l('password')?></label>
      <div class="input-group mb-2">
         <div class="input-group-prepend">
            <div class="input-group-text"><i class="la la-lock"></i></div>
         </div>
         <input type="password" placeholder="<?php _l('password')?>" class="form-control" name="val[password]" >
      </div>
   </div>
   <div  class="text-right">
      <a href="<?php echo url('forgot')?>" data-ajax="true" class="" ><?php _l('forgot-password')?>?</a>
   </div>
   <div>
      <button class="btn btn-block btn-primary btn-lg mt-3"><?php _l('login')?></button>
   </div>
   <div class="signup-frame">
      Don't have an account? <a href="<?php echo url('signup')?>"  data-ajax="true" class="auth-btn rounded"><?php _l('signup')?></a>
   </div>
</form>
