<div class="campaign-start">
    <div id="horizontal-menu" class="pl-2 d-flex align-items-center text-white">
        <span>Start Campaign Confirmation</span>
    </div>
    <div class="content">
        <div class="row  d-flex justify-content-center"><h7>Your campaign has been initiated successfully</h7></div>
        <div class="row  d-flex justify-content-center"><image src="<?php echo assetUrl('assets/images/finish.png')?>"></image></div>
    </div>
</div>
