<div class="campaign-other">
    <div id="horizontal-menu" class="pl-2 d-flex align-items-center text-white">
        <span>Page Engagement</span>
    </div>
    <div class="content campaign-content">
        <div class="row col-md-12">
            <div class=" col-md-3">
                <div class="col-md-12 fb-budget">
                    <div class="col-md-12 pt-3 pb-2 pl-0 ">Facebook</div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6"><h5>20K</h5></div>
                        <div class="col-md-6 text-right p-0"><h5>200AED</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-primary"><h5>Reach</h5></div>
                        <div class="col-md-6 text-primary text-right pr-0"><h5>Spent</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-muted">From Date</div>
                        <div class="col-md-6 text-muted">To Date</div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 "><h7>25 Jul 2020</h7></div>
                        <div class="col-md-6"><h7>25 Jul 2020</h7></div>
                    </div>
                    <div class="col-md-12 pl-0 pt-3">
                        <div class="border-top pt-2 pb-2 p-0">
                            <a class="bluev">Publish Early</a>
                            <a class="float-right text-muted">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" col-md-3">
                <div class="col-md-12 fb-budget">
                    <div class="col-md-12 pt-3 pb-2 pl-0 ">Facebook</div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6"><h5>20K</h5></div>
                        <div class="col-md-6 text-right p-0"><h5>200AED</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-primary"><h5>Reach</h5></div>
                        <div class="col-md-6 text-primary text-right pr-0"><h5>Spent</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-muted">From Date</div>
                        <div class="col-md-6 text-muted">To Date</div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 "><h7>25 Jul 2020</h7></div>
                        <div class="col-md-6"><h7>25 Jul 2020</h7></div>
                    </div>
                    <div class="col-md-12 pl-0 pt-3">
                        <div class="border-top pt-2 pb-2 p-0">
                            <a class="bluev">Publish Early</a>
                            <a class="float-right text-muted">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" col-md-3">
                <div class="col-md-12 fb-budget">
                    <div class="col-md-12 pt-3 pb-2 pl-0 ">Facebook</div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6"><h5>20K</h5></div>
                        <div class="col-md-6 text-right p-0"><h5>200AED</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-primary"><h5>Reach</h5></div>
                        <div class="col-md-6 text-primary text-right pr-0"><h5>Spent</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-muted">From Date</div>
                        <div class="col-md-6 text-muted">To Date</div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 "><h7>25 Jul 2020</h7></div>
                        <div class="col-md-6"><h7>25 Jul 2020</h7></div>
                    </div>
                    <div class="col-md-12 pl-0 pt-3">
                        <div class="border-top pt-2 pb-2 p-0">
                            <a class="bluev">Publish Early</a>
                            <a class="float-right text-muted">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" col-md-3">
                <div class="col-md-12 fb-budget">
                    <div class="col-md-12 pt-3 pb-2 pl-0 ">Facebook</div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6"><h5>20K</h5></div>
                        <div class="col-md-6 text-right p-0"><h5>200AED</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-primary"><h5>Reach</h5></div>
                        <div class="col-md-6 text-primary text-right pr-0"><h5>Spent</h5></div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 text-muted">From Date</div>
                        <div class="col-md-6 text-muted">To Date</div>
                    </div>
                    <div class="col-md-12 row p-0">
                        <div class="col-md-6 "><h7>25 Jul 2020</h7></div>
                        <div class="col-md-6"><h7>25 Jul 2020</h7></div>
                    </div>
                    <div class="col-md-12 pl-0 pt-3">
                        <div class="border-top pt-2 pb-2 p-0">
                            <a class="bluev">Publish Early</a>
                            <a class="float-right text-muted">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row col-md-12 mt-5 d-flex">
            <div class="col-md-1 justify-content-left"><a class="btn arrow-back" href="<?php echo url('post')?>"><i class="las la-arrow-left la-2x text-white"></i></a></div>
            <div class="col-md-11 d-flex justify-content-center"><div class="col-md-2"><a class="btn btn-block btn-primary" href="<?php echo url('post/confirm')?>">PUBLISH</a></div></div>
        </div>
    </div>
</div>