<div id="horizontal-menu">
    <a href="" class="toggle-left menu-toggle-left nav-btn"><i class="la la-chevron-circle-left"></i></a>
    <a href="" class="toggle-right menu-toggle-right nav-btn"><i class="la la-chevron-circle-right"></i></a>
    <div class="menu-container">
        <div class="menu " role="tablist">
            <?php if($design):?>
                <a href="<?php echo url('admin/design')?>" data-ajax="true" class="menu-item "><span><?php _l('design-list')?></span></a>
                <a href="#new" data-toggle="tab" class="menu-item active"><span><?php _l('edit-design')?></span></a>
            <?php else:?>
                <a href="#lists" data-toggle="tab" class="menu-item  active"><span><?php _l('design-list')?></span></a>
                <a href="#new" data-toggle="tab" class="menu-item"><span><?php _l('new-design')?></span></a>
            <?php endif?>
        </div>
    </div>
</div>

<div class="content">
    <div class="tab-content" id="myTabContent">
        <?php if(!$design):?>
            <div class="tab-pane fade show active" id="lists" role="tabpanel" >
                <div class="grid-container clearfix">
                    <?php foreach(model('admin')->getDesigns() as $designObj):?>
                        <div class="each-container">
                            <div  class="each each-design">
                                <div class="color" style="background-color:<?php echo $designObj['primary_color']?>">
                                    <?php if($designObj['is_default']):?>
                                        <div style="position:absolute;top: 7px;left:5px;padding: 6px 10px;border-radius:5px;background:rgba(0,0,0,0.5);color:#fff"><?php _l('default')?></div>
                                    <?php endif?>
                                </div>
                                <div class="bottom clearfix">
                                    <div class="float-left">
                                        <?php echo $designObj['title']?>
                                    </div>
                                    <div class="float-right dropup">
                                        <a href="" data-json='<?php echo json_encode(perfectUnSerialize($designObj['data']))?>' onclick="return preivewDesign(this,'<?php echo $designObj['primary_color']?>')" class="btn btn-light btn-sm mtitle" title="<?php _l('preview-design')?>"><i class="las la-eye"></i></i></a>
                                        <a href="<?php echo url('admin/design/'.$designObj['id'])?>" data-ajax="true" class="btn btn-light btn-sm mtitle" title="<?php _l('edit-design')?>"><i class="la la-pencil"></i></a>
                                        <a href="" data-toggle="dropdown" class="btn btn-light btn-sm"><i class="las la-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item ajax-action" href="<?php echo url('admin/design', array('action'=>'default', 'id' => $designObj['id']))?>"><?php _l('set-default')?></a>
                                            <?php if($designObj['id'] != 1):?>
                                                <a class="dropdown-item confirm" data-ajax-action="true" href="<?php echo url('admin/design', array('action'=>'delete', 'id' => $designObj['id']))?>" data-ajax><?php _l('delete')?></a>
                                            <?php endif?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <?php endforeach;?>
                </div>
            </div>
        <?php endif?>
        <div class="tab-pane fade show <?php echo ($design) ? 'active' :null?>" id="new" role="tabpanel" >
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                <input type="hidden" name="val[action]" value="add"/>
                <div class="form-group">
                    <label><?php _l('design-title')?></label>
                    <input value="<?php echo ($design) ? $design['title'] : null?>" required type="text" class="form-control" name="val[title]"/>
                </div>

                <hr/>

                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('primary-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                type="text"
                                class="color"
                                data-target-bg=".btn-primary"
                                data-target-color="#app-container .side-menu .active i, #app-container .side-menu .active span,#horizontal-menu .menu-container .active span,.thin-menu ul a:hover,.thin-menu ul a.active"
                                data-target-border=".thin-menu ul a.active,.btn-primary"
                                value="<?php echo ($design) ? $design['primary_color'] : '#F98E3B'?>" name="val[primary]"/>
                    </div>
                </div>

                <hr/>
                <?php
                    $data = array();
                    if ($design) $data = perfectUnserialize($design['data']);

                ?>
                <h5><?php _l('collapse-side-menu-design')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('menu-background')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                value="<?php echo (isset($data['col-menu-bg'])) ? $data['col-menu-bg'] : '#fff'?>"
                                data-target-bg="#app-container .left-pane"
                                type="text" class="color" name="val[data][col-menu-bg]"/>
                    </div>
                </div>

                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('menu-link-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color=".thin-menu ul a"
                                type="text" class="color"
                                value="<?php echo (isset($data['col-menu-link-color'])) ? $data['col-menu-link-color'] : '#808080'?>"
                                name="val[data][col-menu-link-color]"/>
                    </div>
                </div>

                <hr/>
                <h5><?php _l('menu-icons-color')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('report-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#report-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['report-icon-color'])) ? $data['report-icon-color'] : '#808080'?>"
                                name="val[data][report-icon-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('rss-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#rss-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['rss-icon-color'])) ? $data['rss-icon-color'] : '#808080'?>"
                                name="val[data][rss-icon-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('captions-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#captions-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['captions-icon-color'])) ? $data['captions-icon-color'] : '#808080'?>"
                                name="val[data][captions-icon-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('filemanager-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#filemanager-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['filemanager-icon-color'])) ? $data['filemanager-icon-color'] : '#808080'?>"
                                name="val[data][filemanager-icon-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('groups-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#groups-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['groups-icon-color'])) ? $data['groups-icon-color'] : '#808080'?>"
                                name="val[data][groups-icon-color]"/>
                    </div>
                </div>

                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('affiliate-icon-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color="#affiliate-icon-color"
                                type="text" class="color"
                                value="<?php echo (isset($data['affiliate-icon-color'])) ? $data['affiliate-icon-color'] : '#808080'?>"
                                name="val[data][affiliate-icon-color]"/>
                    </div>
                </div>

                <hr/>
                <h5><?php _l('expanded-side-menu-design')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('menu-background')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-bg=".opened-menu .left-pane"
                                type="text" class="color"
                                value="<?php echo (isset($data['exp-menu-bg'])) ? $data['exp-menu-bg'] : '#151515'?>"
                                name="val[data][exp-menu-bg]"/>
                    </div>
                </div>

                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('menu-link-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color=".opened-menu .thin-menu ul a"
                                type="text" class="color"
                                value="<?php echo (isset($data['exp-menu-link-color'])) ? $data['exp-menu-link-color'] : '#808080'?>"
                                name="val[data][exp-menu-link-color]"/>
                    </div>
                </div>
                <hr/>
                <h5><?php _l('compose-button')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2 compose-btn-design">
                    <div class="float-left">
                        <input
                                data-target-gradient="#app-container .left-pane .compose-btn,.opened-menu .left-pane .compose-btn"
                                data-container=".compose-btn-design"
                                type="text" class="color first"
                                value="<?php echo (isset($data['compose-first'])) ? $data['compose-first'] : '#ff4d93'?>"
                                name="val[data][compose-first]"/>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-gradient=".compose-btn"
                                data-container=".compose-btn-design"
                                type="text" class="color second"
                                value="<?php echo (isset($data['compose-second'])) ? $data['compose-second'] : '#ff7512'?>"
                                name="val[data][compose-second]"/>
                    </div>
                </div>
                <hr/>
                <h5><?php _l('menu-toggle')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('background-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-bg=".menu-toggle, .sub-menu-toggle"
                                type="text" class="color"
                                value="<?php echo (isset($data['menu-toggle-bg-color'])) ? $data['menu-toggle-bg-color'] : '#fff'?>"
                                name="val[data][menu-toggle-bg-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-color=".menu-toggle, .sub-menu-toggle"
                                type="text" class="color"
                                value="<?php echo (isset($data['menu-toggle-color'])) ? $data['menu-toggle-color'] : '#808080'?>"
                                name="val[data][menu-toggle-color]"/>
                    </div>
                </div>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('border-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-border=".menu-toggle, .sub-menu-toggle"
                                type="text" class="color"
                                value="<?php echo (isset($data['menu-toggle-border-color'])) ? $data['menu-toggle-border-color'] : '#808080'?>"
                                name="val[data][menu-toggle-border-color]"/>
                    </div>
                </div>
                <hr/>
                <h5><?php _l('extra')?></h5>
                <hr/>
                <div class="clearfix mt-3 mb-2">
                    <div class="float-left">
                        <h6 style="font-size:12px;font-weight: 300;"><?php _l('nav-active-background-color')?></h6>
                    </div>
                    <div class="float-right">
                        <input
                                data-target-bg="#app-container .side-menu .active"
                                type="text" class="color"
                                value="<?php echo (isset($data['nav-active-background-color'])) ? $data['nav-active-background-color'] : '#F9FAFB'?>"
                                name="val[data][nav-active-background-color]"/>
                    </div>
                </div>
                <button class="btn btn-primary btn-lg"><?php echo ($design) ? l('save-design'): l('create-design')?></button>
            </form>
        </div>
    </div>
</div>