<div id="horizontal-menu">
    <?php $page = $C->request->input('p')?>
    <div class="menu-container">
        <div class="menu " role="tablist">
            <a href="#users" data-toggle="tab" class="menu-item  <?php echo (!$page) ? 'active' : null?>"><span><?php _l('users')?></span></a>
            <a href="#new" data-toggle="tab" class="menu-item   <?php echo ($page == 'new') ? 'active' : null?>"><span><?php _l('create-new-user')?></span></a>

        </div>
    </div>

    <div class="actions-pane">
        <ul class="clearfix">
            <li>
                <form action="<?php echo getFullUrl()?>" data-container="#users" method="post" class="search-form">
                    <div class="input-group">

                        <input placeholder="<?php _l('enter-a-keyword')?>" value="<?php echo $C->request->input('term')?>" type="text" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
                        <div class="input-group-append">
                            <button class="input-group-text btn btn-primary" id="inputGroupPrepend2"><i class="la la-search"></i></button>
                        </div>
                    </div>
                </form>
            </li>

        </ul>
    </div>
</div>

<div class="content">
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show <?php echo (!$page) ? 'active' : null?>" id="users" role="tabpanel" >
            <?php echo view('admin/users/display', array('users' => $users))?>
        </div>

        <div class="tab-pane fade show <?php echo ($page == 'new') ? 'active' : null?>" id="new" role="tabpanel" >
            <form action="<?php echo getFullUrl(true)?>" method="post" class="general-form short-form">
                <input type="hidden" name="val[create]" value="1"/>
                <div class="form-group">
                    <label><?php _l('full-name')?></label>
                    <input type="text" class="form-control" name="val[full_name]"/>
                </div>

                <div class="form-group">
                    <label><?php _l('email-address')?></label>
                    <input type="text" class="form-control" name="val[email]"/>
                </div>

                <div class="form-group">
                    <label><?php _l('password')?></label>
                    <input type="password" class="form-control" name="val[password]"/>
                </div>

                <div class="form-group">
                    <label><?php _l('confirm-password')?></label>
                    <input type="password" class="form-control" name="val[confirm]"/>
                </div>

                <?php Hook::getInstance()->fire('admin.create.user')?>

                <div class="form-group">
                    <label><?php _l('select-timezone')?></label>
                    <select class="form-control select-timezone" name="val[timezone]">
                        <option value=""><?php _l('select-timezone')?></option>
                        <?php foreach(getTimezones() as $key => $name):?>
                            <option value="<?php echo $key?>"><?php echo $name?></option>
                        <?php endforeach?>
                    </select>
                </div>

                <button class="btn btn-primary btn-lg"><?php _l('create-user')?></button>

            </form>
        </div>


    </div>
</div>