<?php foreach($accounts as $account):?>
    <a href="javascript:void(0)" onclick="return selectThisAccount(this)"
       data-image="<?php echo assetUrl($account['avatar'])?>"
       data-type="<?php echo $account['social_type']?>"
       data-name="<?php echo $account['username']?>"
       data-id="<?php echo $account['id']?>"
       class="clearfix each" style="">
        <div class="float-left">

            <img src="<?php echo assetUrl($account['avatar'])?>" style="width:40px;height:40px;border-radius:100px"/>

            <span style="position:relative;bottom: 5px; font-size: 15px;font-weight: lighter;left:14px"><i class='lab la-<?php echo $account['social_type']?>'></i> <?php echo $account['username']?></span><br/>

        </div>

        <div class="float-right">
            <div class="custom-control custom-checkbox">
                <input onchange="return selectThisAccount(this, true)" value="<?php echo $account['id']?>" type="checkbox" class="custom-control-input" id="customCheck<?php echo $account['id']?>">
                <label class="custom-control-label" for="customCheck<?php echo $account['id']?>"></label>
            </div>
        </div>
    </a>

<?php endforeach?>
